// generated by openstrux-generator — do not edit

import type { ReviewStatus } from "./ReviewStatus.js";

export interface Proposal {
  id: string;
  title: string;
  submitter: string;
  description: string | null;
  submitted_at: Date;
  status: ReviewStatus;
}
