// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// write-data: store-proposal
// TODO: implement write — prisma.<model>.upsert({ ... })

export async function POST(req: NextRequest): Promise<NextResponse> {
  // TODO: implement intake-proposals/intake
  return NextResponse.json({ ok: true });
}
