// generated by openstrux-generator — do not edit

import { z } from "zod";
import { ReviewStatus } from "../types/ReviewStatus.js";

export const ProposalSchema = z.object({
  id: z.string(),
  title: z.string(),
  submitter: z.string(),
  description: z.string().nullable(),
  submitted_at: z.coerce.date(),
  status: z.nativeEnum(ReviewStatus),
});

export type ProposalInput = z.infer<typeof ProposalSchema>;
