// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";
import { ProposalSchema } from "../schemas/Proposal.schema.js";
import { prisma } from "../lib/prisma.js";

export async function POST(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  const input = ProposalSchema.parse(body);
  const result = await prisma.proposal.create({ data: input });
  return NextResponse.json(result, { status: 201 });
}
