// generated by openstrux-generator — do not edit

export enum ReviewStatus {
  draft = "draft",
  submitted = "submitted",
  under_review = "under_review",
  approved = "approved",
  rejected = "rejected",
}
