// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  switch ((body as { kind?: string }).kind) {
    case "eligible":
      // STRUX-STUB: split branch — eligible
      break;
    case "ineligible":
      // STRUX-STUB: split branch — ineligible
      break;
  }
  return NextResponse.json(body, { status: 200 });
}
