// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  const result = (body as unknown[]).filter((item) => item);
  return NextResponse.json(result, { status: 200 });
}
