// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "../lib/prisma.js";

export async function POST(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  const result = await prisma.unknown.create({ data: body });
  return NextResponse.json(result, { status: 201 });
}
