// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  const result = await fetch("https://api.example.com/data", { method: "POST" }).then(r => r.json());
  return NextResponse.json(result, { status: 200 });
}
