// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  /**
   * @compliance encrypt
   * @access scope.fieldMask: ssn, dob
   */
  const result = await encrypt(body, ctx);
  return NextResponse.json(result, { status: 200 });
}
