// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// call: ext-call
async function callExtCall(input: unknown): Promise<unknown> {
  const result = await fetch("https://api.example.com/data", { method: "POST" });
  return result.json();
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  // TODO: implement test-call/receive
  return NextResponse.json({ ok: true });
}
