// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// pseudonymize: anon-op
/**
 * @access scope.fieldMask: email, name
 */
function pseudonymizeAnonOp(input: unknown): unknown {
  // TODO: implement pseudonymize — anon-op
  throw new Error("not implemented");
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  // TODO: implement test-pseudo/receive
  return NextResponse.json({ ok: true });
}
