// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// write-data: store-op
// TODO: implement write — prisma.<model>.create({ data: input })

export async function GET(req: NextRequest): Promise<NextResponse> {
  // TODO: implement test-write-data/receive
  return NextResponse.json({ ok: true });
}
