// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// split: route-split
switch (/* TODO: route-split route key */ undefined) {
  case "eligible":
    // TODO: handle eligible
    break;
  case "ineligible":
    // TODO: handle ineligible
    break;
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  // TODO: implement test-split/receive
  return NextResponse.json({ ok: true });
}
