// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

// transform: eval
function transform(input: Proposal): EligibilityRecord {
  // TODO: implement transform — eval
  throw new Error("not implemented");
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  // TODO: implement test-transform/receive
  return NextResponse.json({ ok: true });
}
